version: '3.4'

networks:
  ivyschoolapp-network:
    driver: bridge 

services:
  ivyschoolapi:
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"     
    networks:
      - ivyschoolapp-network
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./IvySchool.Data/dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mysecretpassword"
      POSTGRES_DB: "IvySchool"
    networks:
      - ivyschoolapp-network
volumes:
  db_volume:
         
    
     